version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./frontend/public:/var/www/html
      - ./frontend/assets:/var/www/html/assets
      - ./frontend/admin:/var/www/html/admin
      - ./backend/controllers:/var/www/html/controllers
      - ./backend/includes:/var/www/html/includes
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: reservacioneskawai
    volumes:
      - db_data:/var/lib/mysql
      - ./devops/mysql-init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db

volumes:
  db_data:
